### ISSUE TITLE
CMake should use c++20 by default

### ISSUE THREAD

**Issue by arijort** [jbcoe/value_types#322] opened 2023-12-08 20:13 UTC
Trying to build value_types on MacOS Monterey out of the box with cmake results in the compilation error below because nothing specifies that we should use c++20:

```
[ 10%] Building CXX object CMakeFiles/indirect_test.dir/indirect_test.cc.o
In file included from /Users/arijort/shadows/value_types/value_types/indirect_test.cc:21:
/Users/arijort/shadows/value_types/value_types/indirect.h:257:19: error: no template named 'three_way_comparable_with' in namespace 'std'; did you mean 'equality_comparable_with'?
    requires std::three_way_comparable_with<T, U>
             ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
                  equality_comparable_with
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/concepts:358:9: note: 'equality_comparable_with' declared here
concept equality_comparable_with =
        ^
1 error generated.
make[2]: *** [CMakeFiles/indirect_test.dir/indirect_test.cc.o] Error 1
make[1]: *** [CMakeFiles/indirect_test.dir/all] Error 2
make: *** [all] Error 2 
$ 
```

**Comment by arijort** [comment] 2023-12-08 20:14
Recipe to repro:
$ git clone ...
$ cd value_types
$ mkdir build ; cd build
$ cmake ..
$ cmake --build .

**Comment by Ukilele** [comment] 2023-12-10 18:08
Hi @arijort , I would love to help with that issue. But looking at your error message leaves me slightly puzzled, as `three_way_comparable_with` does not get used at all in `indirect.h`. And also looking at line 257 of `indirect.h` is no help for me. Could it be that you have an outdated verion? Or am I missing something?

**Comment by arijort** [comment] 2023-12-11 13:45
@Ukilele Hi! I was using that build error as the basis for a PR I'm going to publish later today. Am I using an outdated version to produce this error? I will doublecheck. Need to finish up some work this morning and will get back to it.
Thanks!

**Comment by jbcoe** [comment] 2023-12-11 13:46
Thanks @arijort and @Ukilele - look forward to an update

**Comment by jbcoe** [comment] 2024-01-19 19:01
@arijort I'm going to close this for now as I can't reproduce the issue.

Feel free to re-open if you have instructions for a reproduction.

**Closed by jbcoe** 2024-01-19 19:01 UTC
